### ISSUE TITLE
Multiline support missing

### ISSUE THREAD

**Issue by speedbooster** [JonasRock/ARXML_NavigationHelper#2]
The extension does not collapse the node correctly when there is a multi line tag

Example
>&lt;sometag>text on
>multiple
>lines&lt;/sometag>

The collapsed view still shows:
>multiple
>lines

**Comment by JonasRock** [comment]
Do you refer to the nodes in the "SHORTNAMES" Tree on the left panel with the open editors or the collapsing of text in the text editor?
The latter would be an issue with VSCode's default collapsing of XML files as far as I know.
